---
title: "BMI app to Calculate Body Mass Index"
author: "Monnappa Somanna"
highlighter: highlight.js
output: pdf_document
job: null
knit: slidify::knit2slides
mode: selfcontained
hitheme: tomorrow
subtitle: Data Product for health tracking on the GO!
framework: io2012
widgets: []
---

## BMI App to Calculate Body Mass Index(BMI)*

BMI APP  calaculates the BMI of a person given his/her weight in pounds/Kgs and Height in inches/meters

*Body Mass Index (BMI) is a person's weight in Pounds/kilograms divided by the square of height in inches/meters. A high BMI can be an indicator of high body fatness. BMI can be used to screen for weight categories that may lead to health problems but it is not diagnostic of the body fatness or health of an individual

Please see the link below for more details:
https://en.wikipedia.org/wiki/Body_mass_index

--- .class #id 

## How BMI is calculated

  Body Mass Index is a function of weight in pounds and Height in inches

  Following Mathematical Equation is Embeded in calculating the BMI

        BMI = ((weight / (height * height)) * 703)

  ## User inputs:

    Weight in pounds. Example: 180 pounds

    Height in Inches. Example: 72 inches
    
  ## Results:
  
      Your BMI is...
        [1] 24.40972
        [1] "Normal weight"

--- .class #id 

## Health Tracking using the BMI App

BMI App can be used as your companion to monitor BMI Index on Regular intervals

Following is the key inpterpretation of the results based on BMI:

      >18.5 -Underweight
    
      < 25 - Normal weight
      
      < 30 -Overweight
 
      otherwise Obese

Regular monittoring of the BMI helps to keep track of the help 

--- .class #id 

## Contact us for any clarifications

Thank you for using the BMI APP

For any questions or clarifications contact me at abc@bmiapp.com

Customer support Toll Free: 1800-BMI-APP


